package com.example.persistence.entity;
// Generated Apr 6, 2024, 1:11:40 AM by Hibernate Tools 6.0.2.Final


import com.example.persistence.enums.PerformanceReating;
import jakarta.json.bind.annotation.JsonbTransient;
import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

import java.sql.Date;

/**
 * Performancereview generated by hbm2java
 */
@Entity
@Table(name="performancereview"
    ,catalog="hrapi"
)

public class PerformanceReview implements java.io.Serializable {


     private Integer reviewId;
     @JsonbTransient
     private Employee employee;
     private Date reviewDate;
     private PerformanceReating performanceRating;

     private  Integer  reviwerId;
     private String reviwerName;



    public PerformanceReview() {
    }

    public PerformanceReview(Employee employee, Date reviewDate, PerformanceReating performanceRating) {
       this.employee = employee;
       this.reviewDate = reviewDate;
       this.performanceRating = performanceRating;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ReviewID", unique=true, nullable=false)
    public Integer getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EmployeeID")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ReviewDate", length=10)
    public Date getReviewDate() {
        return this.reviewDate;
    }
    
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }

    
    @Column(name="PerformanceRating", length=9)
    @Enumerated(EnumType.STRING)
    public PerformanceReating getPerformanceRating() {
        return this.performanceRating;
    }
    
    public void setPerformanceRating(PerformanceReating performanceRating) {
        this.performanceRating = performanceRating;
    }


    @Transient
    public Integer getReviwerId() {
        return employee.getEmployeeId();
    }

    @Transient
    public String getReviwerName() {
        return employee.getFirstName() + " " + employee.getLastName();
    }



    @Override
    public String toString() {
        return "PerformanceReview{" +
                "reviewId=" + reviewId +
                ", reviewDate=" + reviewDate +
                ", performanceRating=" + performanceRating +
                '}';
    }
}


