package com.example.persistence.entity;
// Generated Apr 6, 2024, 1:11:40 AM by Hibernate Tools 6.0.2.Final


import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

/**
 * Salary generated by hbm2java
 */
@Entity
@Table(name="salary"
    ,catalog="hrapi"
)
public class Salary  implements java.io.Serializable {


     private Integer salaryId;
     private Employee employee;
     private BigDecimal basicSalary;
     private BigDecimal bonus;
     private BigDecimal deductions;
    private BigDecimal netSalary;

    public Salary() {
    }

    public Salary(Employee employee, BigDecimal basicSalary, BigDecimal bonus, BigDecimal deductions) {
       this.employee = employee;
       this.basicSalary = basicSalary;
       this.bonus = bonus;
       this.deductions = deductions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SalaryID", unique=true, nullable=false)
    public Integer getSalaryId() {
        return this.salaryId;
    }
    
    public void setSalaryId(Integer salaryId) {
        this.salaryId = salaryId;
    }


    @ManyToOne(optional = false)
    @JoinColumn(name="EmployeeID")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="Salary", precision=10, scale=2)
    public BigDecimal getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(BigDecimal basicSalary) {
        this.basicSalary = basicSalary;
    }

    
    @Column(name="Bonus", precision=10, scale=2)
    public BigDecimal getBonus() {
        return this.bonus;
    }
    
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    
    @Column(name="Deductions", precision=10, scale=2)
    public BigDecimal getDeductions() {
        return this.deductions;
    }
    
    public void setDeductions(BigDecimal deductions) {
        this.deductions = deductions;
    }

    @Transient
    public BigDecimal getNetSalary() {
        BigDecimal basic = (this.basicSalary != null) ? this.basicSalary : BigDecimal.ZERO;
        BigDecimal bon = (this.bonus != null) ? this.bonus : BigDecimal.ZERO;
        BigDecimal ded = (this.deductions != null) ? this.deductions : BigDecimal.ZERO;

        return basic.add(bon).subtract(ded);
    }

    public void setNetSalary(BigDecimal netSalary) {
        this.netSalary = netSalary;
    }

    @Override
    public String toString() {
        return "Salary{" +
                "salaryId=" + salaryId +
                ", employee id=" + employee +
                ", salaryBisic=" + basicSalary +
                ", bonus=" + bonus +
                ", deductions=" + deductions +
                '}';
    }
}


